export const fullPerformanceCommands = [
  "pnpm verify:perf",
  "npm run verify:perf",
  "pnpm run --silent verify:perf",
  "pnpm run --if-present verify:perf",
  "pnpm --silent run verify:perf",
  "npm run --silent verify:perf",
  "npm --silent run verify:perf",
  "pnpm --dir . verify:perf",
  "pnpm -C . verify:perf",
  "pnpm -s verify:perf",
  "npm --prefix . run verify:perf",
  "/opt/homebrew/bin/pnpm verify:perf",
] as const;

export const wrappedPerformanceCommands = [
  'sh -c "pnpm verify:perf"',
  'bash -lc "pnpm run verify:perf"',
  "pnpm exec pnpm verify:perf",
  "env pnpm verify:perf",
  "TOOLCRAFT_MODE=full pnpm verify:perf",
  "corepack pnpm verify:perf",
  "npx pnpm verify:perf",
  "node scripts/run-browser-performance.mjs",
  "node --trace-warnings scripts/run-browser-performance.mjs",
  "node -- scripts/run-browser-performance.mjs",
  "env -i node scripts/run-browser-performance.mjs",
  "(pnpm verify:perf)",
  "eval 'pnpm verify:perf'",
  "pnpm verify\\:perf",
  "echo verify:perf",
  "rg verify:perf docs",
  'node -e "console.log(\'verify:perf\')"',
] as const;
